FROM node:14 as builder

RUN mkdir -p /frontend
WORKDIR /frontend

COPY package.json /frontend
RUN npm install 

COPY . /frontend

RUN npm run build

FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /frontend/build /usr/share/nginx/html